
#ifndef _OX_TRADE_API_CONST_H_
#define _OX_TRADE_API_CONST_H_

const int OX_ERRORINFO_LENGTH = 128;
//2023-09-14 shibx modify 资金账号长度从16调整成24
const int OX_ACCOUNT_LENGTH = 24;
const int OX_PASSWORD_LENGTH = 16;
const int OX_RESERVED_LENGTH = 256;

const int OX_BOARDID_LENGTH = 4;
const int OX_SYMBOL_LENGTH = 36;       //20221221 长度从12调整为36
const int OX_ORDERID_LENGTH = 16;
const int OX_QUERYPOS_LENGTH = 36;

//2023-06-27  长度从16调整成24
const int OX_TRDACCT_LENGTH = 24;
const int OX_ORDERPRICE_LENGTH = 16;
//2023-09-14 shibx modify 资金账号长度从16调整成24
const int OX_CUSTCODE_LENGTH = 24;
const int OX_CASHNO_LENGTH = 16;

const int OX_OPTNUM_LENGTH = 12;
const int OX_OPTUNDLCODE_LENGTH = 12;
const int OX_STKPBU_LENGTH = 8;
const int OX_ORDERTIME_LENGTH = 36;

const int OX_EXEINFO_LENGTH = 128;
const int OX_FILLEDAMT_LENGTH = 24;

const int OX_ACCOUNTWORTH_LENGTH = 24;
const int OX_FUNDVALUE_LENGTH = 24;
const int OX_MARKETVALUE_LENGTH = 24;
const int OX_FUNDPREBALANCE_LENGTH = 24;

const int OX_FUNDBALANCE_LENGTH = 24;
const int OX_AVAIABLE_LENGTH = 24;
const int OX_STKNAME_LENGTH = 16;

const int OX_STKBCOST_LENGTH = 24;
const int OX_STKBCOSTRLT_LENGTH = 24;
const int OX_STKPLAMT_LENGTH = 24;
const int OX_STKPLAMTRLT_LENGTH = 24;
const int OX_MKTVA_LENGTH = 24;
const int OX_COSTPRICE_LENGTH = 16;
const int OX_PROINCOME_LENGTH = 24;
const int OX_STKCALMKTVALE_LENGTH = 2;
const int OX_CURRENTPRICE_LENGTH = 16;
const int OX_PROFITPRICE_LENGTH = 16;

const int OX_AVERAGEPRICE_LENGTH = 16;
const int OX_INCOME_LENGTH = 24;

const int OX_TRADESN_LENGTH = 36;

const int OX_FILLEDPRICE_LENGTH = 16;
const int OX_FILLEDTIME_LENGTH = 12;

const int OX_RETMESSAGE_LENGTH = 128;

const int OX_SUBACCTCODE_LENGTH = 12;
const int OX_OPTTRDACCT_LENGTH = 24;


const int OX_OPTCODE_LENGTH = 36;

const int OX_OPTNAME_LENGTH = 36;

const int OX_ETF_PRICE_INFO = 10240;

const int OX_STRATEGY_TEXT = 32768;

const int OX_RET_INFO_LENGTH = 256;

const int OX_CREDIT_DOUBLE_LENGTH = 24;

const int OX_ORDER_REF_LENGTH = 33;

const int OX_OPTBCOST_LENGTH = 32;
const int OX_OPTBCOSTRLT_LENGTH = 32;
const int OX_OPTPLAMT_LENGTH = 32;
const int OX_OPTPLAMTRLT_LENGTH = 32;
const int OX_OPTMKTVAL_LENGTH = 32;
const int OX_OPTPREMIUM_LENGTH = 32;
const int OX_OPTMARGIN_LENGTH = 32;
const int OX_OPTCVDASSET_LENGTH = 32;
const int OX_OPTCLSPROFIT_LENGTH = 32;
const int OX_SUMCLSPROFIT_LENGTH = 32;
const int OX_OPTFLOATPROFIT_LENGTH = 32;
const int OX_TOTALPROFIT_LENGTH = 32;

const int OX_ETFCASHRATIO_LENGTH = 16;
const int OX_ETFESTMCASH_LENGTH = 16;
const int OX_ETFCASHCOMP_LENGTH = 16;
const int OX_ETFNAVPERCU_LENGTH = 16;
const int OX_ETFNAV_LENGTH = 16;

const int OX_ETFOVERFLOWRATE_LENGTH = 16;
const int OX_REDEMPTIONINSTEADAMT_LENGTH = 16;
const int OX_CREATIONINSTEADAMT_LENGTH = 16;
const int OX_ETFDISCOUNTRATE_LENGTH = 16;

const int OX_TRD_EXT_INFO_LENGTH = 512;

const int MAX_ORDERS_COUNT = 500;

#endif
